version: 0.0
os: linux

files:
  - source: home/circleci/project/webapp/target/webapp-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/

hooks:
  ApplicationStart:
   - location: ./afterInstall.sh
     timeout: 180
     runas: ubuntu
