---
version: 2
jobs:
  build:
    docker:
      - image : circleci/openjdk:11.0.5-jdk-stretch
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: root123
          MYSQL_PASSWORD: root123
    steps:
      - checkout
      - run:
          name: Testing circleci
          command: echo "Hello World! Welcome circleci"
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Step into webApplication
          command: |
             pwd
             cd Assignment2
             ls -al
             sudo apt-get update
             sudo apt install maven
             mvn clean install
             

workflows:
  version: 2
  build_deploy:
    jobs:
    - build